### ISSUE TITLE
Crashes if number of orbitals exceeds ca. 256

### ISSUE THREAD

**Issue by mkrompiec** [CQCL/pyscf-ac0#7]
@conodp could you please enter the description of the error/limitation
Basis size `nbas`, 1-electron integral table size `NInte1` and  ERI table size `two_el_size` should be integer(8), not integer(4). Moreover, the dimension of `eig` was incorrect.

**Comment by conodp** [comment]
For large number of orbitals calculations of 2-electron size index was given an overflow due to low integer precision assign to the variable. Also, the mismatch between size declaration of arrays in two different subroutines threw the 'malloc(): unsupported double linked list corrupted'

**Comment by mkrompiec** [comment]
BTW, these issues weren't present in the original GAMMCOR code but were introduced by me when converting to f90.
